services:
    oro_sync.websocket_client:
        alias: oro_sync.websocket_client.basic

    oro_sync.websocket_client.basic:
        class: 'Oro\Bundle\SyncBundle\Client\WebsocketClient'
        public: false
        arguments:
            - '@oro_sync.client.factory.gos'
            - '@oro_sync.authentication.ticket_provider'
            - '%websocket_backend_host%'
            - '%websocket_backend_port%'
            - '%websocket_backend_path%'

    oro_sync.client.factory.gos:
        class: 'Oro\Bundle\SyncBundle\Client\Factory\GosClientFactory'
        public: false

    oro_sync.client.logger_aware_decorator:
        class: 'Oro\Bundle\SyncBundle\Client\LoggerAwareWebsocketClientDecorator'
        decorates: oro_sync.websocket_client
        arguments:
            - '@oro_sync.client.logger_aware_decorator.inner'
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: oro_websocket }

    oro_sync.client.manipulator:
        class: 'Oro\Bundle\SyncBundle\Client\ClientManipulator'
        decorates: gos_web_socket.websocket.client_manipulator
        arguments:
            - '@oro_sync.client.manipulator.inner'
            - '@gos_web_socket.client_storage'
            - '@oro_user.security.provider'
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: oro_websocket }
