parameters:
    oro_wamp.publisher.class:             Oro\Bundle\SyncBundle\Wamp\TopicPublisher
    oro_wamp.db_ping.class:               Oro\Bundle\SyncBundle\Wamp\DbPing
    oro_wamp.listener.clank.class:        Oro\Bundle\SyncBundle\EventListener\OroWampEventListener
    oro_wamp.listener.maintenance.class:  Oro\Bundle\SyncBundle\EventListener\OroMaintenanceEventListener

services:
    oro_wamp.publisher:
        class:                            %oro_wamp.publisher.class%
        arguments:
            - %websocket_host%
            - %websocket_port%

    oro_wamp.db_ping:
        class:                            %oro_wamp.db_ping.class%
        arguments:
            - "@doctrine.dbal.default.wrapped_connection"

    kernel.listener.clank.event:
        class:                            %oro_wamp.listener.clank.class%
        arguments:
            - "@session.handler.pdo"
            - "@security.context"
            - %session.storage.options%
        tags:
            - { name: kernel.event_listener, event: clank.client.connected, method: onClientConnect }

    kernel.listener.maintenance.event:
        class:                            %oro_wamp.listener.maintenance.class%
        arguments:
            - "@oro_wamp.publisher"
        tags:
            - { name: kernel.event_listener, event: maintenance.on, method: onModeOn }
            - { name: kernel.event_listener, event: maintenance.off, method: onModeOff }
