gos_web_socket:
    client:
        firewall: ~
    server:
        port: "%websocket_bind_port%"      # The port the socket server will listen on
        host: "%websocket_bind_address%"   # (optional) The host ip to bind to
        router:
            resources: ~

    # We don`t need assets of GosWebSocketBundle
    assetic: false
    # We don`t need server connection parameters provided by GosWebSocketBundle in TWIG.
    shared_config: false

twig:
    globals:
        ws:
            port:       "%websocket_frontend_port%"  # Websocket port used in JS
            host:       "%websocket_frontend_host%"  # Websocket host used in JS
            path:       "%websocket_frontend_path%"  # Websocket request path used in JS

monolog:
    channels:
        - oro_websocket
    handlers:
        websocket:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL:       WARNING
                VERBOSITY_VERBOSE:      NOTICE
                VERBOSITY_VERY_VERBOSE: INFO
                VERBOSITY_DEBUG:        DEBUG
            channels:
                type: inclusive
                elements:
                    - oro_websocket
