config:
    map:
        '*':
            'autobahn': 'orosync/js/extend/autobahn'
        'orosync/js/extend/autobahn':
            'autobahn': 'autobahn'
    paths:
        'when': 'bundles/bowerassets/when/when.js'
        'autobahn': 'bundles/bowerassets/autobahnjs/autobahn/autobahn.js'
        'orosync/js/content/grid-builder': 'bundles/orosync/js/content/grid-builder.js'
        'orosync/js/content-manager': 'bundles/orosync/js/content-manager.js'
        'orosync/js/app/modules/content-manager-module': 'bundles/orosync/js/app/modules/content-manager-module.js'
    appmodules:
        - orosync/js/app/modules/content-manager-module
